var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(roles)/web-admin/settings/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__ba30cc68._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_0fe7a407._.js")
R.c("server/chunks/ssr/[root-of-the-server]__9cfc4081._.js")
R.c("server/chunks/ssr/node_modules_63dba3f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__a1762fd7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/src_app_(roles)_web-admin_layout_tsx_57302f97._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(roles)_web-admin_settings_page_actions_9c8c47d7.js")
R.m(9282)
module.exports=R.m(9282).exports
