var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(roles)/web-admin/classes/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__87a6d894._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_b9c1c84f._.js")
R.c("server/chunks/ssr/[root-of-the-server]__9cfc4081._.js")
R.c("server/chunks/ssr/node_modules_63dba3f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__a1762fd7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/src_app_(roles)_web-admin_layout_tsx_57302f97._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(roles)_web-admin_classes_page_actions_a830ad54.js")
R.m(96908)
module.exports=R.m(96908).exports
