var R=require("../../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(roles)/teacher/enrolled-classes/[id]/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__264440d0._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_bc594bb9._.js")
R.c("server/chunks/ssr/[root-of-the-server]__9cfc4081._.js")
R.c("server/chunks/ssr/node_modules_63dba3f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__a1762fd7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/src_app_(roles)_teacher_layout_tsx_7727e9cb._.js")
R.c("server/chunks/ssr/ce889_server_app_(roles)_teacher_enrolled-classes_[id]_page_actions_4e23125f.js")
R.m(73301)
module.exports=R.m(73301).exports
