var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(roles)/teacher/earning/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__2f7cc85e._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_7c55a8f6._.js")
R.c("server/chunks/ssr/[root-of-the-server]__9cfc4081._.js")
R.c("server/chunks/ssr/node_modules_63dba3f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__a1762fd7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/src_app_(roles)_teacher_layout_tsx_7727e9cb._.js")
R.c("server/chunks/ssr/_next-internal_server_app_(roles)_teacher_earning_page_actions_bbb09615.js")
R.m(10654)
module.exports=R.m(10654).exports
