var R=require("../../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(roles)/web-admin/withdrawal-request/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__e566e8a8._.js")
R.c("server/chunks/ssr/_0efddc1b._.js")
R.c("server/chunks/ssr/_d87ca3ed._.js")
R.c("server/chunks/ssr/[root-of-the-server]__9cfc4081._.js")
R.c("server/chunks/ssr/node_modules_63dba3f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_70ed294b._.js")
R.c("server/chunks/ssr/src_app_5b2047f8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__a1762fd7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/src_app_(roles)_web-admin_layout_tsx_57302f97._.js")
R.c("server/chunks/ssr/ce889_server_app_(roles)_web-admin_withdrawal-request_page_actions_fe1c4f3a.js")
R.m(31118)
module.exports=R.m(31118).exports
