// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/app-admin" | "/auth" | "/auth/forgot-password" | "/auth/otp" | "/auth/reset-password" | "/checkout" | "/classes" | "/classes/%5BclassId%5D" | "/classes/[id]" | "/classes/enrolled-classes" | "/faq" | "/messages" | "/payment/error" | "/payment/success" | "/privacy" | "/profile" | "/student" | "/support" | "/teacher" | "/teacher/classes" | "/teacher/earning" | "/teacher/enrolled-classes" | "/teacher/enrolled-classes/[id]" | "/teacher/messages" | "/teacher/profile" | "/teacher/settings" | "/terms" | "/tutors" | "/tutors/[id]" | "/web-admin" | "/web-admin/classes" | "/web-admin/payment" | "/web-admin/privacy" | "/web-admin/profile" | "/web-admin/settings" | "/web-admin/student" | "/web-admin/student/[id]" | "/web-admin/teacher" | "/web-admin/teacher/[id]" | "/web-admin/terms" | "/web-admin/withdrawal-request" | "/web-admin/withdrawal-request/[id]"
type PageRoutes = never
type LayoutRoutes = "/" | "/auth" | "/teacher" | "/web-admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/app-admin": {}
  "/auth": {}
  "/auth/forgot-password": {}
  "/auth/otp": {}
  "/auth/reset-password": {}
  "/checkout": {}
  "/classes": {}
  "/classes/[id]": { "id": string; }
  "/classes/%5BclassId%5D": {}
  "/classes/enrolled-classes": {}
  "/faq": {}
  "/messages": {}
  "/payment/error": {}
  "/payment/success": {}
  "/privacy": {}
  "/profile": {}
  "/student": {}
  "/support": {}
  "/teacher": {}
  "/teacher/classes": {}
  "/teacher/earning": {}
  "/teacher/enrolled-classes": {}
  "/teacher/enrolled-classes/[id]": { "id": string; }
  "/teacher/messages": {}
  "/teacher/profile": {}
  "/teacher/settings": {}
  "/terms": {}
  "/tutors": {}
  "/tutors/[id]": { "id": string; }
  "/web-admin": {}
  "/web-admin/classes": {}
  "/web-admin/payment": {}
  "/web-admin/privacy": {}
  "/web-admin/profile": {}
  "/web-admin/settings": {}
  "/web-admin/student": {}
  "/web-admin/student/[id]": { "id": string; }
  "/web-admin/teacher": {}
  "/web-admin/teacher/[id]": { "id": string; }
  "/web-admin/terms": {}
  "/web-admin/withdrawal-request": {}
  "/web-admin/withdrawal-request/[id]": { "id": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/auth": never
  "/teacher": never
  "/web-admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
