// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../src/app/(roles)/app-admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app-admin">> = Specific
  const handler = {} as typeof import("../../src/app/(roles)/app-admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(roles)/student/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/student">> = Specific
  const handler = {} as typeof import("../../src/app/(roles)/student/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(roles)/teacher/classes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/classes">> = Specific
  const handler = {} as typeof import("../../src/app/(roles)/teacher/classes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(roles)/teacher/earning/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/earning">> = Specific
  const handler = {} as typeof import("../../src/app/(roles)/teacher/earning/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(roles)/teacher/enrolled-classes/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/enrolled-classes/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(roles)/teacher/enrolled-classes/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(roles)/teacher/enrolled-classes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/enrolled-classes">> = Specific
  const handler = {} as typeof import("../../src/app/(roles)/teacher/enrolled-classes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(roles)/teacher/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/messages">> = Specific
  const handler = {} as typeof import("../../src/app/(roles)/teacher/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(roles)/teacher/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher">> = Specific
  const handler = {} as typeof import("../../src/app/(roles)/teacher/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(roles)/teacher/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/profile">> = Specific
  const handler = {} as typeof import("../../src/app/(roles)/teacher/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(roles)/teacher/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teacher/settings">> = Specific
  const handler = {} as typeof import("../../src/app/(roles)/teacher/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(roles)/web-admin/classes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/web-admin/classes">> = Specific
  const handler = {} as typeof import("../../src/app/(roles)/web-admin/classes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(roles)/web-admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/web-admin">> = Specific
  const handler = {} as typeof import("../../src/app/(roles)/web-admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(roles)/web-admin/payment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/web-admin/payment">> = Specific
  const handler = {} as typeof import("../../src/app/(roles)/web-admin/payment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(roles)/web-admin/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/web-admin/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/(roles)/web-admin/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(roles)/web-admin/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/web-admin/profile">> = Specific
  const handler = {} as typeof import("../../src/app/(roles)/web-admin/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(roles)/web-admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/web-admin/settings">> = Specific
  const handler = {} as typeof import("../../src/app/(roles)/web-admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(roles)/web-admin/student/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/web-admin/student/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(roles)/web-admin/student/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(roles)/web-admin/student/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/web-admin/student">> = Specific
  const handler = {} as typeof import("../../src/app/(roles)/web-admin/student/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(roles)/web-admin/teacher/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/web-admin/teacher/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(roles)/web-admin/teacher/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(roles)/web-admin/teacher/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/web-admin/teacher">> = Specific
  const handler = {} as typeof import("../../src/app/(roles)/web-admin/teacher/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(roles)/web-admin/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/web-admin/terms">> = Specific
  const handler = {} as typeof import("../../src/app/(roles)/web-admin/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(roles)/web-admin/withdrawal-request/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/web-admin/withdrawal-request/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/(roles)/web-admin/withdrawal-request/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(roles)/web-admin/withdrawal-request/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/web-admin/withdrawal-request">> = Specific
  const handler = {} as typeof import("../../src/app/(roles)/web-admin/withdrawal-request/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/forgot-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/forgot-password">> = Specific
  const handler = {} as typeof import("../../src/app/auth/forgot-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/otp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/otp">> = Specific
  const handler = {} as typeof import("../../src/app/auth/otp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth">> = Specific
  const handler = {} as typeof import("../../src/app/auth/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/reset-password/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/auth/reset-password/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/checkout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/checkout">> = Specific
  const handler = {} as typeof import("../../src/app/checkout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/classes/%5BclassId%5D/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/classes/%5BclassId%5D">> = Specific
  const handler = {} as typeof import("../../src/app/classes/%5BclassId%5D/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/classes/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/classes/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/classes/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/classes/enrolled-classes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/classes/enrolled-classes">> = Specific
  const handler = {} as typeof import("../../src/app/classes/enrolled-classes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/classes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/classes">> = Specific
  const handler = {} as typeof import("../../src/app/classes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faq">> = Specific
  const handler = {} as typeof import("../../src/app/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/messages/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/messages">> = Specific
  const handler = {} as typeof import("../../src/app/messages/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/payment/error/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payment/error">> = Specific
  const handler = {} as typeof import("../../src/app/payment/error/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/payment/success/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/payment/success">> = Specific
  const handler = {} as typeof import("../../src/app/payment/success/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/privacy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy">> = Specific
  const handler = {} as typeof import("../../src/app/privacy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../src/app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/support/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/support">> = Specific
  const handler = {} as typeof import("../../src/app/support/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/terms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms">> = Specific
  const handler = {} as typeof import("../../src/app/terms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tutors/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tutors/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/tutors/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tutors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tutors">> = Specific
  const handler = {} as typeof import("../../src/app/tutors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../src/app/(roles)/teacher/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/teacher">> = Specific
  const handler = {} as typeof import("../../src/app/(roles)/teacher/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/(roles)/web-admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/web-admin">> = Specific
  const handler = {} as typeof import("../../src/app/(roles)/web-admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/auth/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/auth">> = Specific
  const handler = {} as typeof import("../../src/app/auth/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
